
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL is the Supabase direct connection (port 5432).
    // Falls back to DATABASE_URL so prisma generate works in CI without it.
    url: process.env.DIRECT_URL,
    shadowDatabaseUrl: process.env.DATABASE_URL
  },
});
